# Animal Shelter Outcome Improvement {#NineLives}

#### Keywords

Animal Shelter Euthanasia

## Overview

The American Society for the Prevention of Cruelty to Animals (ASPCA) estimates that 6.5 million animals arrive at shelters each year.  The majority of the shelter animals are comprised of strays, rescues, and surrenders.  Many of these animals are returned to their owners or are adopted, but others are not so fortunate.  It is estimated that 1.5 million animals are euthanized each year, representing a considerable loss of life and expense while sheltering these animals.  Shelters, along with the many people who donate to them, have a desire to see that their money is spent in a way that brings about the most favorable outcomes to as many animals as possible.  If shelters could predict the outcomes of animals better (being returned to their owner, adopted, euthanized, etc.) they could focus their energies to improve the likelihood that more animals survive.

## Solution

The proposed solution is a predictive model for the outcome of animals brought into shelters.  This would be provided as a web based service to shelters.

As animals are brought into a shelter, information about the animal would be entered into the service, such as their type (dog/cat), breed, sex, spay/neuter status, age, color, temperament, and the reason why they were brought in (stray, rescue, surrender).  If the animal was a surrender, a sub-classification would be made if it was due to a health issue, behavioral issue, or housing concern (i.e. pet restriction where the owners live).  If the animal was a stray, the age of the animal would need to be estimated, and there are existing methods to do this.  Note that some animals have a microchip that indicates the animals’ ID, which can be matched to a national database to retrieve information about the animal.  In this case, the shelter’s first step would be to enter the animal’s ID into an optional field, and any information that could be obtained about the animal would be populated.

This data would be presented to a classification model that would indicate the likelihood that the animal would be adopted, returned, or euthanized.  The system would also provide a recommendation on how the animal’s outcome could be improved, along with the revised probabilities for the animal’s outcome after the recommendation has occurred.  The shelter could use this information to make its animals more favorable for adoption.  For instance, sick animals would be treated by veterinarians, and animals with behavioral issues could be given training.  The probability score would be used to budget resources in case there are judgements that need to be made on which animals to focus on, when resources are limited.

The service would be cloud based, and could scale up and support many shelters.   A predictive model would be created for each shelter, as the demand for animals may vary between regions.  The service would provide a web-based portal so that people who would like to adopt an animal can search for one online.  A future enhancement to this service would be the addition of another model that matches animals with people who are looking to adopt a pet.

## Saved Lives

The large number of animals brought to shelters that end up languishing there or are euthanized is unfortunate.  Data science can be used to help alleviate this tragedy by helping shelters focus resources on animals to improve their outcomes.  The resulting increase in adoption rates and reduction in euthanasia fulfills the desires of both the shelters and those who support them.
